@baseUrl = http://localhost:8082

### 1. 初始化库存 - 正常
POST {{baseUrl}}/api/v1/inventory/init
Content-Type: application/json

{
  "product_id": 1,
  "stock_quantity": 100
}

### 2. 增加库存 - 正常
POST {{baseUrl}}/api/v1/inventory/add
Content-Type: application/json

{
  "product_id": 13,
  "quantity": 20
}

### 3. 增加库存 - quantity = 0，应返回参数错误
POST {{baseUrl}}/api/v1/inventory/add
Content-Type: application/json

{
  "product_id": 11,
  "quantity": 0
}

### 4. 增加库存 - 未初始化库存，应失败
### 说明：先创建一个商品，但不要初始化库存
### 然后对这个 product_id 调用 AddInventory
### 预期 ErrInventoryNotFound
POST {{baseUrl}}/api/v1/inventory/add
Content-Type: application/json

{
  "product_id": 11,
  "quantity": 20
}

### 5. 查询商品库存
GET {{baseUrl}}/api/v1/inventory/products/1

### 6. 查询商品库存 - 非法 product_id
GET {{baseUrl}}/api/v1/inventory/products/abc

### 7. 查询商品库存 - 不存在
GET {{baseUrl}}/api/v1/inventory/products/999999