@baseUrl = http://localhost:8082

### 1. 查询全部库存流水
GET {{baseUrl}}/api/v1/stock-logs

### 2. 查询指定商品库存流水
GET {{baseUrl}}/api/v1/stock-logs?product_id=1

### 3. 查询库存流水 - 非法 product_id
GET {{baseUrl}}/api/v1/stock-logs?product_id=0

### 4. 查询库存流水 - 非数字 product_id
GET {{baseUrl}}/api/v1/stock-logs?product_id=abc